### ISSUE TITLE
you code can't got bool expression from netlist 

### ISSUE THREAD

**Issue by dengzailin** [rodrigowue/s2cae#1]
Hi 
I have a little test case about AND , but has error as below:
NMOS:
20:XMM19_1 net030 net034
21:XMM19_2 net030 net034
22:XMM19_3 net030 net034
23:XMM20_1 net034 net038
24:XMM20_2 net034 net038
25:XMM20_3 net034 net038
26:XMM21_1 net038 VSS
27:XMM21_2 net038 VSS
28:XMM21_3 net038 VSS
29:XMM22_1 net26 net030
30:XMM22_2 net26 net030
31:XMM22_3 net26 net030
32:XMM5_1 Z VSS
33:XMM5_2 Z VSS
34:XMM5_3 Z VSS
35:XMM5_4 Z VSS
36:XMM5_5 Z VSS
37:XMM5_6 Z VSS
38:XMM5_7 Z VSS
39:XMM5_8 Z VSS
input:A1
input:A2
input:A3
input:A4
output:Z
Z=
Z=
net26=
net26=(net26*(net26*(A4*(A3*(A2*A1)))))
!(*)
!(*(net26*(net26*(A4*(A3*(A2*A1))))))
it2:!(*(net26*(net26*(A4*(A3*(A2*A1))))))
exp:!(*(net26*(net26*(A4*(A3*(A2*A1))))))
commo:net26
what_it_will_be:!(*(net26*(net26*(A4*(A3*(A2*A1))))))
Result:!(*(!(*(net26*(net26*(A4*(A3*(A2*A1))))))*(!(*(net26*(net26*(A4*(A3*(A2*A1))))))*(A4*(A3*(A2*A1))))))
Expression: !(*)

the netlist as below:

 1 .subckt AN4D8BWP16P90CPD A1 A2 A3 A4 Z VDD VSS VPP VBB
  2 XMM16_1         net26           A3              VDD             VPP             P12             L=0.016u        nfin=4          as=5.698e-15
  3 XMM16_2         net26           A3              VDD             VPP             P12             L=0.016u        nfin=4
  4 XMM16_3         net26           A3              VDD             VPP             P12             L=0.016u        nfin=4          as=5.698e-15
  5 XMM17_1         net26           A1              VDD             VPP             P12             L=0.016u        nfin=4          as=5.544e-15
  6 XMM17_2         net26           A1              VDD             VPP             P12             L=0.016u        nfin=4
  7 XMM17_3         net26           A1              VDD             VPP             P12             L=0.016u        nfin=4          as=5.698e-15
  8 XMM18_1         net26           A2              VDD             VPP             P12             L=0.016u        nfin=4
9 XMM18_2         net26           A2              VDD             VPP             P12             L=0.016u        nfin=4          as=5.698e-15
 10 XMM18_3         net26           A2              VDD             VPP             P12             L=0.016u        nfin=4
 11 XMM19_1         net030          A2              net034          VBB             N12             L=0.016u        nfin=4
 12 XMM19_2         net030          A2              net034          VBB             N12             L=0.016u        nfin=4          as=5.698e-15
 13 XMM19_3         net030          A2              net034          VBB             N12             L=0.016u        nfin=4
 14 XMM20_1         net034          A3              net038          VBB             N12             L=0.016u        nfin=4
 15 XMM20_2         net034          A3              net038          VBB             N12             L=0.016u        nfin=4          as=5.698e-15
 16 XMM20_3         net034          A3              net038          VBB             N12            
17 XMM21_1         net038          A4              VSS             VBB             N12             L=0.016u        nfin=4
 18 XMM21_2         net038          A4              VSS             VBB             N12             L=0.016u        nfin=4          as=5.698e-15
 19 XMM21_3         net038          A4              VSS             VBB             N12             L=0.016u        nfin=4
 20 XMM22_1         net26           A1              net030          VBB             N12             L=0.016u        nfin=4
 21 XMM22_2         net26           A1              net030          VBB             N12             L=0.016u        nfin=4          as=5.698e-15
 22 XMM22_3         net26           A1              net030          VBB             N12             L=0.016u        nfin=4
 23 XMM23_1         net26           A4              VDD             VPP             P12             L=0.016u        nfin=4
 24 XMM23_2         net26           A4              VDD             VPP             P12             L=0.016u        nfin
25 XMM23_3         net26           A4              VDD             VPP             P12             L=0.016u        nfin=4
 26 XMM4_1          Z               net26           VDD             VPP             P12             L=0.016u        nfin=4          as=5.698e-15
 27 XMM4_2          Z               net26           VDD             VPP             P12             L=0.016u        nfin=4
 28 XMM4_3          Z               net26           VDD             VPP             P12             L=0.016u        nfin=4          as=5.698e-15
 29 XMM4_4          Z               net26           VDD             VPP             P12             L=0.016u        nfin=4
 30 XMM4_5          Z               net26           VDD             VPP             P12             L=0.016u        nfin=4          as=5.698e-15
 31 XMM4_6          Z               net26           VDD             VPP             P12             L=0.016u        nfin=4
 32 XMM4_7          Z               net26           VDD             VPP             P12           
33 XMM4_8          Z               net26           VDD             VPP             P12             L=0.016u        nfin=4
 34 XMM5_1          Z               net26           VSS             VBB             N12             L=0.016u        nfin=4          as=5.698e-15
 35 XMM5_2          Z               net26           VSS             VBB             N12             L=0.016u        nfin=4
 36 XMM5_3          Z               net26           VSS             VBB             N12             L=0.016u        nfin=4          as=5.698e-15
 37 XMM5_4          Z               net26           VSS             VBB             N12             L=0.016u        nfin=4
 38 XMM5_5          Z               net26           VSS             VBB             N12             L=0.016u        nfin=4          as=5.698e-15
 39 XMM5_6          Z               net26           VSS             VBB             N12             L=0.016u        nfin=4
40 XMM5_7          Z               net26           VSS             VBB             N12             L=0.016u        nfin=4          as=5.698e-15
 41 XMM5_8          Z               net26           VSS             VBB             N12             L=0.016u        nfin=4
.ends

please help me

**Comment by rodrigowue** [comment]
Dear @dengzailin ,

Thanks for you feedback on the tool. I am developing it by myself and it is currently under development.

I still need to do some changes to work with standard cells that has more than 1 common net between the pull-down and pull-up networks. I will include your spice description under my tests so I can work to make it fully functional.

Best Regards,
Rodrigo

**Comment by dengzailin** [comment]
> 
ok , thanks your reply ,   I have other question  the sequential cell like Latch,DFF .  dou you plan to develop ?

**Comment by rodrigowue** [comment]
Hi,

Yes. The idea I am working on is to retrieve the boolean for each of these
"common nets". In order to work with the sequential cells I will need to do
some sort of temporal activation of each net to see which activation order
triggers the output.

So each common net will have it is own arcs and it will be used as inputs
for the following stages.

Em sáb., 11 de mar. de 2023 10:12, dengzailin ***@***.***>
escreveu:

**Comment by rodrigowue** [comment]
Hi,

Just to let you know that I am working on the issue and it is almost ready to work. Now I need to do the part that merges all expressions. It is detection your circuit as a NAND but it is a AND. There is an issue with the replacement part that I am investigating.

```
======================================
 SPICE STD-CELL TIMING ARCS EXTRACTOR
       [UNDER DEVELOPMENT]
======================================
Subcircuit:AN4D8BWP16P90CPD
----------------------------------------
PMOS:
0:XMM16_1 net26 A3 VDD
1:XMM16_2 net26 A3 VDD
2:XMM16_3 net26 A3 VDD
3:XMM17_1 net26 A1 VDD
4:XMM17_2 net26 A1 VDD
5:XMM17_3 net26 A1 VDD
6:XMM18_1 net26 A2 VDD
7:XMM18_2 net26 A2 VDD
8:XMM18_3 net26 A2 VDD
9:XMM23_1 net26 A4 VDD
10:XMM23_2 net26 A4 VDD
11:XMM23_3 net26 A4 VDD
12:XMM4_1 Z net26 VDD
13:XMM4_2 Z net26 VDD
14:XMM4_3 Z net26 VDD
15:XMM4_4 Z net26 VDD
16:XMM4_5 Z net26 VDD
17:XMM4_6 Z net26 VDD
18:XMM4_7 Z net26 VDD
19:XMM4_8 Z net26 VDD
NMOS:
20:XMM19_1 net030 A2 net034
21:XMM19_2 net030 A2 net034
22:XMM19_3 net030 A2 net034
23:XMM20_1 net034 A3 net038
24:XMM20_2 net034 A3 net038
25:XMM20_3 net034 A3 net038
26:XMM21_1 net038 A4 VSS
27:XMM21_2 net038 A4 VSS
28:XMM21_3 net038 A4 VSS
29:XMM22_1 net26 A1 net030
30:XMM22_2 net26 A1 net030
31:XMM22_3 net26 A1 net030
32:XMM5_1 Z net26 VSS
33:XMM5_2 Z net26 VSS
34:XMM5_3 Z net26 VSS
35:XMM5_4 Z net26 VSS
36:XMM5_5 Z net26 VSS
37:XMM5_6 Z net26 VSS
38:XMM5_7 Z net26 VSS
39:XMM5_8 Z net26 VSS
----------------------------------------
Inputs & Outputs
input:A1
input:A2
input:A3
input:A4
output:Z
----------------------------------------
Z=(((net26+net26)+(net26+net26))+((net26+net26)+(net26+net26)))
net26=(((A2+A4)+(A4+A4))+(((A3+A3)+(A3+A1))+((A1+A1)+(A2+A2))))
Z=(((net26+net26)+(net26+net26))+((net26+net26)+(net26+net26)))
net26=((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3)))))
----------------------------------------
Expression After Flattening: !(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))
----------------------------------------
TRUTH TABLE:
0000|1
1000|1
0100|1
1100|1
0010|1
1010|1
0110|1
1110|1
0001|1
1001|1
0101|1
1101|1
0011|1
1011|1
0111|1
1111|0
ARCS:
Number of literals: 1
Segmentation fault ```

**Comment by rodrigowue** [comment]
Truth table is working. Now I am working to make the arcs retrieval functional because I am getting a segmentation fault with this.

**Comment by rodrigowue** [comment]
Working!!!!

```
======================================
 SPICE STD-CELL TIMING ARCS EXTRACTOR
       [UNDER DEVELOPMENT]
======================================
Subcircuit:AN4D8BWP16P90CPD
----------------------------------------
PMOS:
0:XMM16_1 net26 A3 VDD
1:XMM16_2 net26 A3 VDD
2:XMM16_3 net26 A3 VDD
3:XMM17_1 net26 A1 VDD
4:XMM17_2 net26 A1 VDD
5:XMM17_3 net26 A1 VDD
6:XMM18_1 net26 A2 VDD
7:XMM18_2 net26 A2 VDD
8:XMM18_3 net26 A2 VDD
9:XMM23_1 net26 A4 VDD
10:XMM23_2 net26 A4 VDD
11:XMM23_3 net26 A4 VDD
12:XMM4_1 Z net26 VDD
13:XMM4_2 Z net26 VDD
14:XMM4_3 Z net26 VDD
15:XMM4_4 Z net26 VDD
16:XMM4_5 Z net26 VDD
17:XMM4_6 Z net26 VDD
18:XMM4_7 Z net26 VDD
19:XMM4_8 Z net26 VDD
NMOS:
20:XMM19_1 net030 A2 net034
21:XMM19_2 net030 A2 net034
22:XMM19_3 net030 A2 net034
23:XMM20_1 net034 A3 net038
24:XMM20_2 net034 A3 net038
25:XMM20_3 net034 A3 net038
26:XMM21_1 net038 A4 VSS
27:XMM21_2 net038 A4 VSS
28:XMM21_3 net038 A4 VSS
29:XMM22_1 net26 A1 net030
30:XMM22_2 net26 A1 net030
31:XMM22_3 net26 A1 net030
32:XMM5_1 Z net26 VSS
33:XMM5_2 Z net26 VSS
34:XMM5_3 Z net26 VSS
35:XMM5_4 Z net26 VSS
36:XMM5_5 Z net26 VSS
37:XMM5_6 Z net26 VSS
38:XMM5_7 Z net26 VSS
39:XMM5_8 Z net26 VSS
----------------------------------------
Inputs & Outputs
input:A1
input:A2
input:A3
input:A4
output:Z
----------------------------------------
Z=(((net26+net26)+(net26+net26))+((net26+net26)+(net26+net26)))
net26=(((A2+A4)+(A4+A4))+(((A3+A3)+(A3+A1))+((A1+A1)+(A2+A2))))
Z=(((net26+net26)+(net26+net26))+((net26+net26)+(net26+net26)))
net26=((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3)))))
----------------------------------------
Expression After Flattening: !((((!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))+!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3)))))))+(!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))+!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))))+((!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))+!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3)))))))+(!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))+!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))))))
----------------------------------------
TRUTH TABLE:
0000|0
1000|0
0100|0
1100|0
0010|0
1010|0
0110|0
1110|0
0001|0
1001|0
0101|0
1101|0
0011|0
1011|0
0111|0
1111|1
ARCS:
Number of literals: 4
1 1 1 F  | Fall
1 1 F 1  | Fall
1 F 1 1  | Fall
F 1 1 1  | Fall
R 1 1 1  | Rise
1 R 1 1  | Rise
1 1 R 1  | Rise
1 1 1 R  | Rise
----------------------------------------
```

**Comment by dengzailin** [comment]
great!  could you give me some method for sequential cell got the function. ?










At 2023-03-14 02:20:01, "Rodrigo Nogueira Wuerdig" ***@***.***> wrote:

Working!!!!

======================================
 SPICE STD-CELL TIMING ARCS EXTRACTOR
       [UNDER DEVELOPMENT]
======================================
Subcircuit:AN4D8BWP16P90CPD
----------------------------------------
PMOS:
0:XMM16_1 net26 A3 VDD
1:XMM16_2 net26 A3 VDD
2:XMM16_3 net26 A3 VDD
3:XMM17_1 net26 A1 VDD
4:XMM17_2 net26 A1 VDD
5:XMM17_3 net26 A1 VDD
6:XMM18_1 net26 A2 VDD
7:XMM18_2 net26 A2 VDD
8:XMM18_3 net26 A2 VDD
9:XMM23_1 net26 A4 VDD
10:XMM23_2 net26 A4 VDD
11:XMM23_3 net26 A4 VDD
12:XMM4_1 Z net26 VDD
13:XMM4_2 Z net26 VDD
14:XMM4_3 Z net26 VDD
15:XMM4_4 Z net26 VDD
16:XMM4_5 Z net26 VDD
17:XMM4_6 Z net26 VDD
18:XMM4_7 Z net26 VDD
19:XMM4_8 Z net26 VDD
NMOS:
20:XMM19_1 net030 A2 net034
21:XMM19_2 net030 A2 net034
22:XMM19_3 net030 A2 net034
23:XMM20_1 net034 A3 net038
24:XMM20_2 net034 A3 net038
25:XMM20_3 net034 A3 net038
26:XMM21_1 net038 A4 VSS
27:XMM21_2 net038 A4 VSS
28:XMM21_3 net038 A4 VSS
29:XMM22_1 net26 A1 net030
30:XMM22_2 net26 A1 net030
31:XMM22_3 net26 A1 net030
32:XMM5_1 Z net26 VSS
33:XMM5_2 Z net26 VSS
34:XMM5_3 Z net26 VSS
35:XMM5_4 Z net26 VSS
36:XMM5_5 Z net26 VSS
37:XMM5_6 Z net26 VSS
38:XMM5_7 Z net26 VSS
39:XMM5_8 Z net26 VSS
----------------------------------------
Inputs & Outputs
input:A1
input:A2
input:A3
input:A4
output:Z
----------------------------------------
Z=(((net26+net26)+(net26+net26))+((net26+net26)+(net26+net26)))
net26=(((A2+A4)+(A4+A4))+(((A3+A3)+(A3+A1))+((A1+A1)+(A2+A2))))
Z=(((net26+net26)+(net26+net26))+((net26+net26)+(net26+net26)))
net26=((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3)))))
----------------------------------------
Expression After Flattening: !((((!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))+!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3)))))))+(!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))+!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))))+((!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))+!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3)))))))+(!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))+!(((A1+(A1+A1))*((A4+(A4+A4))*((A2+(A2+A2))*(A3+(A3+A3))))))))))
----------------------------------------
TRUTH TABLE:
0000|0
1000|0
0100|0
1100|0
0010|0
1010|0
0110|0
1110|0
0001|0
1001|0
0101|0
1101|0
0011|0
1011|0
0111|0
1111|1
ARCS:
Number of literals: 4
1 1 1 F  | Fall
1 1 F 1  | Fall
1 F 1 1  | Fall
F 1 1 1  | Fall
R 1 1 1  | Rise
1 R 1 1  | Rise
1 1 R 1  | Rise
1 1 1 R  | Rise
----------------------------------------
